"""add_senha_atualizada_em_to_usuarios

Revision ID: 43a33c2431bb
Revises: eb71a38a6f10
Create Date: 2026-08-03 07:41:33.984820

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43a33c2431bb'
down_revision: str | None = 'eb71a38a6f10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha_atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'senha_atualizada_em')
    # ### end Alembic commands ###
