"""criar tabelas setores e setor_usuarios

Revision ID: 561d6626ca37
Revises: 43a33c2431bb
Create Date: 2026-09-15 17:42:44.937789

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "561d6626ca37"
down_revision: str | None = "43a33c2431bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_setores_nome"), "setores", ["nome"], unique=True)
    op.create_table(
        "setor_usuarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("setor_id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("papel", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["setor_id"],
            ["setores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("setor_id", "usuario_id", name="uq_setor_usuario"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("setor_usuarios")
    op.drop_index(op.f("ix_setores_nome"), table_name="setores")
    op.drop_table("setores")
    # ### end Alembic commands ###
