"""criar tabela status_usuarios e substituir ativo por status_id

Revision ID: 88ce9743a2f1
Revises: 6d90c1c19995
Create Date: 2026-07-30 11:40:47.146303

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88ce9743a2f1'
down_revision: str | None = '6d90c1c19995'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_usuarios_nome'), 'status_usuarios', ['nome'], unique=True)
    
    # 1. Inserir status padrão
    op.execute("INSERT INTO status_usuarios (id, nome) VALUES ('1fa85f64-5717-4562-b3fc-2c963f66afa1', 'pendente')")
    op.execute("INSERT INTO status_usuarios (id, nome) VALUES ('1fa85f64-5717-4562-b3fc-2c963f66afa2', 'ativo')")
    op.execute("INSERT INTO status_usuarios (id, nome) VALUES ('1fa85f64-5717-4562-b3fc-2c963f66afa3', 'inativo')")
    
    # 2. Atualizar usuários antigos para 'ativo' para evitar falha de NOT NULL
    op.execute("UPDATE usuarios SET status_id = '1fa85f64-5717-4562-b3fc-2c963f66afa2' WHERE status_id IS NULL")

    op.alter_column('usuarios', 'status_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_usuarios_curso_id_cursos', 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'cursos', ['curso_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'status_usuarios', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key('fk_usuarios_curso_id_cursos', 'usuarios', 'cursos', ['curso_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('usuarios', 'status_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_status_usuarios_nome'), table_name='status_usuarios')
    op.drop_table('status_usuarios')
    # ### end Alembic commands ###
