"""criar tabelas usuarios

Revision ID: d9a07eade5bf
Revises: 
Create Date: 2026-07-08 14:44:23.557186

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9a07eade5bf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_ingresso', sa.Date(), nullable=False),
    sa.Column('meta_horas_semanais', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('global_role', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_matricula'), 'usuarios', ['matricula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_matricula'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
