"""criar tabela de cargos e fk em usuarios

Revision ID: eb71a38a6f10
Revises: 88ce9743a2f1
Create Date: 2026-07-30 12:02:54.292480

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb71a38a6f10'
down_revision: str | None = '88ce9743a2f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_nome'), 'cargos', ['nome'], unique=True)
    
    # 1. Inserir cargos padrão
    op.execute("INSERT INTO cargos (id, nome) VALUES ('2fa85f64-5717-4562-b3fc-2c963f66afa1', 'super_admin')")
    op.execute("INSERT INTO cargos (id, nome) VALUES ('2fa85f64-5717-4562-b3fc-2c963f66afa2', 'admin')")
    op.execute("INSERT INTO cargos (id, nome) VALUES ('2fa85f64-5717-4562-b3fc-2c963f66afa3', 'aluno')")
    
    # 2. Atualizar usuários existentes para 'aluno'
    op.execute("UPDATE usuarios SET global_role = '2fa85f64-5717-4562-b3fc-2c963f66afa3' WHERE global_role IS NULL")

    op.alter_column('usuarios', 'global_role',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'usuarios', 'cargos', ['global_role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.alter_column('usuarios', 'global_role',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_cargos_nome'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
